#!/usr/bin/env bash

set -e

SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOTDIR="$(git -C "$SCRIPTDIR" rev-parse --show-toplevel)"

set -x

# Generate AUTHORS file
cat > "${ROOTDIR}/AUTHORS" <<- EOF
	# File generated by Gen-Authors.sh. DO NOT EDIT.
	# This file lists all contributors to the repository.
	# See Gen-Authors.sh to make modifications.

	$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF

